{% set version = "1.0.1" %}

package:
  name: resonance_pip
  version: {{ version }}

source:
  git_url: https://github.com/tz-lom/Resonance-PyProj.git
  git_rev: {{version}}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pip
    - python
    - numpy_ringbuffer 
    - scipy
  run:
    - numpy
    - python
    - numpy_ringbuffer 
    - scipy

test:
  imports:
    - resonance

about:
  home: https://github.com/tz-lom/Resonance-PyProj
  license: MIT
  license_family: MIT
  summary: "Python package for Resonance"

extra:
  recipe-maintainers:
    - tz-lom
