{% set data = load_setup_py_data() %}

package:
  name: resonance_pip
  version: {{ data['version'] }}

source:
  git_url: https://github.com/tz-lom/Resonance-PyProj.git
  git_rev: {{ data['version'] }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pip
    - python
    - numpy_ringbuffer 
    - scipy
  run:
    - numpy
    - python
    - numpy_ringbuffer 
    - scipy

test:
  imports:
    - resonance

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}

extra:
  recipe-maintainers:
    - tz-lom
