package:
  name: resonance_pip
  version: {{ GIT_VERSION }}  # git describe --tags --abbrev=0

source:
  git_url: https://github.com/tz-lom/Resonance-PyProj.git
  git_rev: {{ GIT_COMMIT_ID }}  # git describe --tags --abbrev=0

build:
  number: {{ GIT_BUILD_NUMBER }}  # git rev-list  `git rev-list --tags --no-walk --max-count=1`..HEAD --count
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools
  run:
    - numpy
    - numpy_ringbuffer
    - scipy

test:
  imports:
    - resonance

about:
  home: https://github.com/tz-lom/Resonance-PyProj.git
  license: MIT
summary: Resonance python package

extra:
  recipe-maintainers:
    - tz-lom
