name: publish_conda

on: 
  push:
    branches:
    - master
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: tz-lom/conda-publish-action@v1.3
      with:
        subDir: 'conda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'win osx linux'
        channels: 'conda-forge bcilab'
